import{s as h,i as l,S as g}from"./assets/vendor-B4AbC4-x.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const p="48573229-d00ec4466a1952407b35369c3",L="https://pixabay.com/api/";async function u(r,o=1){const n=`${L}?key=${p}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const s=await fetch(n);if(!s.ok)throw new Error("Sorry, there was an error loading. Please try again!");return await s.json()}catch(s){throw console.error(s),s}}function f({webformatURL:r,largeImageURL:o,tags:n,likes:s,views:e,comments:t,downloads:a}){return`
        <a href="${o}" class="gallery-item">
            <img src="${r}" alt="${n}" class="gallery-image" />
            <div class="info">
                <p class="text-image"><b>Likes:</b> ${s}</p>
                <p class="text-image"><b>Views:</b> ${e}</p>
                <p class="text-image"><b>Comments:</b> ${t}</p>
                <p class="text-image"><b>Downloads:</b> ${a}</p>
            </div>
        </a>
    `}function b(r){const o=document.querySelector(".gallery");o.innerHTML=r.map(f).join("")}function c(r){const o=document.querySelector(".load-more");r?o.classList.remove("hidden"):o.classList.add("hidden")}function S(r){document.querySelector(".gallery").insertAdjacentHTML("beforeend",r.map(f).join(""))}function m(){const r=document.querySelector(".gallery");r.innerHTML=""}h.polyfill();let i=1,d="",y=0;document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector("#search-form"),o=r.querySelector("input"),n=document.createElement("button");n.textContent="Load more",n.classList.add("load-more","hidden"),document.querySelector("div").appendChild(n),r.addEventListener("submit",async e=>{e.preventDefault();const t=o.value.trim();if(!t){l.error({title:"Error",message:"Please enter your request."}),m(),c(!1);return}d=t,i=1,document.querySelector(".loader").classList.remove("hidden");try{const a=await u(d,i);y=a.totalHits,m(),a.hits.length===0?(l.info({title:"No Results",message:"Sorry, your request is incorrect. Please try again!"}),c(!1)):(b(a.hits),new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),c(a.hits.length===15))}catch{l.error({title:"Error",message:"Sorry, there was an error. Please try again!"})}finally{document.querySelector(".loader").classList.add("hidden")}});function s(){const e=document.querySelector(".gallery"),{height:t}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*4,behavior:"smooth"})}n.addEventListener("click",async()=>{i+=1,document.querySelector(".loader").classList.remove("hidden");try{const e=await u(d,i);S(e.hits),lightbox.refresh(),s(),(i*15>=y||e.hits.length<15)&&(c(!1),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{l.error({title:"Error",message:"An error occurred: the image could not be loaded. Please try again!"})}finally{document.querySelector(".loader").classList.add("hidden")}})});
//# sourceMappingURL=index.js.map
