import{a as f,S as p,i as a}from"./assets/vendor-Bi0bPHun.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const m=(r,e)=>{const o={params:{key:"48573229-d00ec4466a1952407b35369c3",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15}};return f.get("https://pixabay.com/api/",o)};function y({webformatURL:r,largeImageURL:e,tags:o,likes:l,views:t,comments:s,downloads:n}){return`
        <a href="${e}" class="gallery-item">
            <img src="${r}" alt="${o}" class="gallery-image" />
            <div class="info">
                <p class="text-image"><b>Likes:</b> ${l}</p>
                <p class="text-image"><b>Views:</b> ${t}</p>
                <p class="text-image"><b>Comments:</b> ${s}</p>
                <p class="text-image"><b>Downloads:</b> ${n}</p>
            </div>
        </a>
    `}const b=document.querySelector(".js-form"),u=document.querySelector(".js-gallery"),i=document.querySelector(".js-load-more-btn");let d="",c=1;const g=15,L=new p(".gallery a",{captionsData:"alt",captionDelay:250}),v=async r=>{try{r.preventDefault();const e=r.currentTarget.elements.searchQuery.value.trim();if(e===""){a.error({title:"Error",message:"Please enter your request"});return}e!==d&&(d=e,c=1,u.innerHTML="",i.classList.add("hidden"));const o=await m(d,c);if(o.data.hits.length===0){a.error({title:"Error",message:"Sorry, your request is incorrect. Please try again!"});return}h(o.data.hits),a.success({title:"Success",message:`Found ${o.data.totalHits} images!`}),o.data.totalHits>g&&i.classList.remove("hidden")}catch(e){a.error({title:"Error",message:"Sorry, there was an error. Please try again!"}),console.log(e)}},E=async()=>{try{c+=1,i.classList.add("hidden");const r=await m(d,c);if(r.data.hits.length===0){a.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),i.classList.add("hidden");return}h(r.data.hits),c*g>=r.data.totalHits?(a.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),i.classList.add("hidden")):i.classList.remove("hidden");const{height:e}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(r){a.error({title:"Error",message:"An error occurred: the image could not be loaded. Please try again!"}),console.error(r)}},h=r=>{const e=r.map(y).join("");u.insertAdjacentHTML("beforeend",e),L.refresh()};b.addEventListener("submit",v);i.addEventListener("click",E);
//# sourceMappingURL=index.js.map
